# Generated by Django 3.2.11 on 2022-06-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='post', max_length=250, unique_for_date='publish'),
        ),
    ]
