# Generated by Django 3.2.11 on 2022-06-30 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='activare',
            new_name='active',
        ),
    ]
